// Helper function to capitalize struct names
function capitalize(str) {
    if (!str) return 'AutoGenerated';
    return str.charAt(0).toUpperCase() + str.slice(1);
}

// Convert JSON to Go Struct
export function jsonToGo(jsonStr, structName = 'Config') {
    try {
        const obj = JSON.parse(jsonStr);
        const structs = [];
        
        function parseObject(o, name) {
            const currentStructName = capitalize(name);
            let fields = [];
            
            for (const key in o) {
                if (Object.prototype.hasOwnProperty.call(o, key)) {
                    const value = o[key];
                    const fieldName = key.split(/[-_]/).map(capitalize).join('');
                    let goType = 'interface{}';
                    
                    if (value === null) {
                        goType = 'interface{}';
                    } else if (typeof value === 'string') {
                        goType = 'string';
                    } else if (typeof value === 'number') {
                        goType = Number.isInteger(value) ? 'int' : 'float64';
                    } else if (typeof value === 'boolean') {
                        goType = 'bool';
                    } else if (Array.isArray(value)) {
                        if (value.length === 0) {
                            goType = '[]interface{}';
                        } else {
                            const first = value[0];
                            if (typeof first === 'object' && first !== null) {
                                const subName = currentStructName + capitalize(key) + 'Item';
                                parseObject(first, subName);
                                goType = `[]${subName}`;
                            } else {
                                const typeMap = { 'string': 'string', 'number': Number.isInteger(first) ? 'int' : 'float64', 'boolean': 'bool' };
                                goType = `[]${typeMap[typeof first] || 'interface{}'}`;
                            }
                        }
                    } else if (typeof value === 'object') {
                        const subName = currentStructName + capitalize(key);
                        parseObject(value, subName);
                        goType = subName;
                    }
                    
                    fields.push(`\t${fieldName} ${goType} \`json:"${key}"\``);
                }
            }
            
            structs.push(`type ${currentStructName} struct {\n${fields.join('\n')}\n}`);
        }
        
        if (Array.isArray(obj)) {
            if (obj.length > 0) {
                parseObject(obj[0], structName);
                return `type ${structName}List []${capitalize(structName)}\n\n` + structs.reverse().join('\n\n');
            } else {
                return `type ${structName} []interface{}`;
            }
        } else if (typeof obj === 'object' && obj !== null) {
            parseObject(obj, structName);
            return structs.reverse().join('\n\n');
        } else {
            return `// Input is primitive type: ${typeof obj}`;
        }
    } catch (e) {
        throw new Error('Invalid JSON: ' + e.message);
    }
}

// Convert Go Struct to JSON
export function goToJson(goStr) {
    try {
        const lines = goStr.split('\n');
        const result = {};
        let currentStruct = null;
        const structs = {};

        // Parse structures
        for (let i = 0; i < lines.length; i++) {
            const line = lines[i].trim();
            if (line.startsWith('type ') && line.includes('struct {')) {
                const match = line.match(/type\s+(\w+)\s+struct/);
                if (match) {
                    currentStruct = match[1];
                    structs[currentStruct] = {};
                }
            } else if (line === '}') {
                currentStruct = null;
            } else if (currentStruct && line !== '') {
                // Parse struct field
                // Example: Key string `json:"key"`
                // Regex matches fieldName, type, jsonTag
                const match = line.match(/^(\w+)\s+([\[\]\w\.\{\}]+)(?:\s+`json:"([^"]+)"`)?/);
                if (match) {
                    const [, fieldName, goType, jsonTag] = match;
                    const key = jsonTag ? jsonTag.split(',')[0] : fieldName;
                    structs[currentStruct][key] = goType;
                }
            }
        }

        // Build mock value for a type
        function getMockValue(typeStr) {
            if (!typeStr) return null;
            const cleanedType = typeStr.replace('[]', '').trim();
            const isArray = typeStr.startsWith('[]');

            let val;
            if (cleanedType === 'string') {
                val = "string_value";
            } else if (['int', 'int64', 'float64', 'float32', 'uint'].includes(cleanedType)) {
                val = 123;
            } else if (cleanedType === 'bool') {
                val = true;
            } else if (structs[cleanedType]) {
                val = {};
                for (const key in structs[cleanedType]) {
                    val[key] = getMockValue(structs[cleanedType][key]);
                }
            } else {
                val = null;
            }

            return isArray ? [val] : val;
        }

        // Generate JSON matching the first struct found
        const firstStruct = Object.keys(structs)[0];
        if (!firstStruct) {
            return JSON.stringify({ error: "No struct found" }, null, 2);
        }

        const mockObj = {};
        for (const key in structs[firstStruct]) {
            mockObj[key] = getMockValue(structs[firstStruct][key]);
        }

        return JSON.stringify(mockObj, null, 2);
    } catch (e) {
        throw new Error('Failed to parse Go struct: ' + e.message);
    }
}

// Convert JSON to TypeScript
export function jsonToTs(jsonStr, typeName = 'UserResponse') {
    try {
        const obj = JSON.parse(jsonStr);
        const interfaces = [];
        
        function parseObject(o, name) {
            const currentInterfaceName = capitalize(name);
            let fields = [];
            
            for (const key in o) {
                if (Object.prototype.hasOwnProperty.call(o, key)) {
                    const value = o[key];
                    let tsType = 'any';
                    
                    if (value === null) {
                        tsType = 'any';
                    } else if (typeof value === 'string') {
                        tsType = 'string';
                    } else if (typeof value === 'number') {
                        tsType = 'number';
                    } else if (typeof value === 'boolean') {
                        tsType = 'boolean';
                    } else if (Array.isArray(value)) {
                        if (value.length === 0) {
                            tsType = 'any[]';
                        } else {
                            const first = value[0];
                            if (typeof first === 'object' && first !== null) {
                                const subName = currentInterfaceName + capitalize(key) + 'Item';
                                parseObject(first, subName);
                                tsType = `${subName}[]`;
                            } else {
                                tsType = `${typeof first}[]`;
                            }
                        }
                    } else if (typeof value === 'object') {
                        const subName = currentInterfaceName + capitalize(key);
                        parseObject(value, subName);
                        tsType = subName;
                    }
                    
                    fields.push(`  ${key}: ${tsType};`);
                }
            }
            
            interfaces.push(`export interface ${currentInterfaceName} {\n${fields.join('\n')}\n}`);
        }
        
        if (Array.isArray(obj)) {
            if (obj.length > 0) {
                parseObject(obj[0], typeName);
                return `export type ${typeName}List = ${capitalize(typeName)}[];\n\n` + interfaces.reverse().join('\n\n');
            } else {
                return `export type ${typeName} = any[];`;
            }
        } else if (typeof obj === 'object' && obj !== null) {
            parseObject(obj, typeName);
            return interfaces.reverse().join('\n\n');
        } else {
            return `export type ${typeName} = ${typeof obj};`;
        }
    } catch (e) {
        throw new Error('Invalid JSON: ' + e.message);
    }
}

// Convert TypeScript to JSON
export function tsToJson(tsStr) {
    try {
        const lines = tsStr.split('\n');
        const interfaces = {};
        let currentInterface = null;

        for (let i = 0; i < lines.length; i++) {
            const line = lines[i].trim();
            if ((line.startsWith('export interface ') || line.startsWith('interface ')) && line.includes('{')) {
                const match = line.match(/(?:export\s+)?interface\s+(\w+)/);
                if (match) {
                    currentInterface = match[1];
                    interfaces[currentInterface] = {};
                }
            } else if (line === '}') {
                currentInterface = null;
            } else if (currentInterface && line !== '') {
                // Parse interface field
                // Example: name?: string; or role: string;
                const match = line.match(/^(\w+)(\?)?\s*:\s*([^;]+);?/);
                if (match) {
                    const [, fieldName, , tsType] = match;
                    interfaces[currentInterface][fieldName] = tsType.trim();
                }
            }
        }

        function getMockValue(typeStr) {
            if (!typeStr) return null;
            const cleanedType = typeStr.replace('[]', '').trim();
            const isArray = typeStr.includes('[]');

            let val;
            if (cleanedType === 'string') {
                val = "string_value";
            } else if (cleanedType === 'number') {
                val = 456;
            } else if (cleanedType === 'boolean') {
                val = false;
            } else if (interfaces[cleanedType]) {
                val = {};
                for (const key in interfaces[cleanedType]) {
                    val[key] = getMockValue(interfaces[cleanedType][key]);
                }
            } else {
                val = null;
            }

            return isArray ? [val] : val;
        }

        const firstInterface = Object.keys(interfaces)[0];
        if (!firstInterface) {
            return JSON.stringify({ error: "No interface found" }, null, 2);
        }

        const mockObj = {};
        for (const key in interfaces[firstInterface]) {
            mockObj[key] = getMockValue(interfaces[firstInterface][key]);
        }

        return JSON.stringify(mockObj, null, 2);
    } catch (e) {
        throw new Error('Failed to parse TS interface: ' + e.message);
    }
}

// Escapes JSON into a stringified version
export function escapeJson(jsonStr) {
    try {
        const obj = JSON.parse(jsonStr);
        return JSON.stringify(JSON.stringify(obj));
    } catch (e) {
        // If not valid JSON, try to escape it as a generic string
        return JSON.stringify(jsonStr);
    }
}

// Unescapes stringified JSON
export function unescapeJson(escapedStr) {
    try {
        let current = escapedStr.trim();
        // Remove enclosing quotes if it's double stringified
        if (current.startsWith('"') && current.endsWith('"')) {
            current = JSON.parse(current);
        }
        
        // Parse the inner JSON to ensure validity
        const obj = JSON.parse(current);
        return JSON.stringify(obj, null, 2);
    } catch (e) {
        // Attempt custom regex-based backslash removal if JSON.parse fails
        try {
            const stripped = escapedStr.replace(/\\"/g, '"').replace(/\\\\/g, '\\');
            const obj = JSON.parse(stripped);
            return JSON.stringify(obj, null, 2);
        } catch (innerErr) {
            throw new Error('Failed to unescape/parse JSON: ' + e.message);
        }
    }
}

// Convert Kubernetes Secret YAML to .env or linux export format
export function k8sToEnv(yamlStr, useExport = false) {
    try {
        const lines = yamlStr.split('\n');
        let inDataSection = false;
        let envVars = [];
        let sectionIndent = -1;

        for (let i = 0; i < lines.length; i++) {
            const line = lines[i];
            const trimmed = line.trim();
            if (trimmed === '') continue;

            const indent = line.length - line.trimStart().length;

            if (trimmed.startsWith('data:') || trimmed.startsWith('stringData:')) {
                inDataSection = true;
                sectionIndent = indent;
                continue;
            }

            if (inDataSection) {
                if (indent <= sectionIndent) {
                    // Left data section
                    inDataSection = false;
                } else {
                    const colonIndex = trimmed.indexOf(':');
                    if (colonIndex !== -1) {
                        const key = trimmed.slice(0, colonIndex).trim();
                        let rawVal = trimmed.slice(colonIndex + 1).trim();
                        // Strip quotes if any
                        if (rawVal.startsWith('"') && rawVal.endsWith('"')) {
                            rawVal = rawVal.slice(1, -1);
                        } else if (rawVal.startsWith("'") && rawVal.endsWith("'")) {
                            rawVal = rawVal.slice(1, -1);
                        }
                        
                        let decodedVal = rawVal;
                        // Try base64 decoding
                        try {
                            decodedVal = atob(rawVal);
                        } catch (b64err) {
                            // If not base64 encoded, keep as is
                        }
                        
                        if (useExport) {
                            envVars.push(`export ${key}="${decodedVal.replace(/"/g, '\\"')}"`);
                        } else {
                            envVars.push(`${key}=${decodedVal}`);
                        }
                    }
                }
            }
        }

        if (envVars.length === 0) {
            return '# No secret fields found in YAML data:\n# Ensure they are under "data:" or "stringData:"';
        }

        return envVars.join('\n');
    } catch (e) {
        throw new Error('Failed to parse YAML: ' + e.message);
    }
}

// Convert .env variables to Kubernetes Secret YAML
export function envToK8s(envStr, secretName = 'app-secrets') {
    try {
        const lines = envStr.split('\n');
        const dataEntries = [];

        for (let i = 0; i < lines.length; i++) {
            let line = lines[i].trim();
            if (line === '' || line.startsWith('#')) continue;

            // Strip "export " prefix if present (e.g. export KEY=val)
            if (line.startsWith('export ')) {
                line = line.slice(7).trim();
            }

            const eqIndex = line.indexOf('=');
            if (eqIndex !== -1) {
                const key = line.slice(0, eqIndex).trim();
                let value = line.slice(eqIndex + 1).trim();
                
                // Strip quotes if any
                if (value.startsWith('"') && value.endsWith('"')) {
                    value = value.slice(1, -1);
                } else if (value.startsWith("'") && value.endsWith("'")) {
                    value = value.slice(1, -1);
                }
                const base64Value = btoa(value);
                dataEntries.push(`  ${key}: ${base64Value}`);
            }
        }

        if (dataEntries.length === 0) {
            throw new Error('No valid env/export entries found (format KEY=value or export KEY=value)');
        }

        return `apiVersion: v1
kind: Secret
metadata:
  name: ${secretName || 'app-secrets'}
type: Opaque
data:
${dataEntries.join('\n')}`;
    } catch (e) {
        throw new Error(e.message);
    }
}
